[package]
name = "CAA-Project"
version = "0.1.0"
edition = "2021"

[dependencies]
inquire = "0.7.5"
argon2 = "0.5.3"
rand = "0.8.4"
rand_core = "0.6.4"
hex = "0.4.3"
ecies = "0.2.7"
aes-gcm = "0.10.3"
generic-array = "0.14.7"
ed25519-dalek = "2.1.1"